name: Print GitHub Event Context

on:
  workflow_dispatch:

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo "$EVENT_CONTEXT"
